# Markdown snippets

[opt_global_max_cache_age]
value = """\
  Maximal timespan to preserve the package's [pkgpins](https://pkgpins.rpkg.dev/) cache. Cache entries older than this will be deleted upon package loading.\
  """

[pkg_config]
value = """\
  Some of { pkg }'s functionality is controlled via package-specific global configuration which can either be set via \
  [R options](https://rdrr.io/r/base/options.html) or [environment variables](https://en.wikipedia.org/wiki/Environment_variable) (the former take \
  precedence). This configuration includes:\
  """

[pkg_required]
value = "To be able to use this function, the package '{ pkg }' is required but it is not installed. Please install it and then try again."

[pkgdown_notice]
value = "The documentation of this package is found [here]({ ''; pkgdown::as_pkgdown()$meta$url })."

[rstudio_addin_hint]
value = """\
  This function is also registered as an [RStudio add-in](https://rstudio.github.io/rstudioaddins/), allowing RStudio users to assign a \
  [custom shortcut](https://support.rstudio.com/hc/en-us/articles/206382178-Customizing-Keyboard-Shortcuts-in-the-RStudio-IDE) to it and to invoke it from the \
  [command palette](https://www.rstudio.com/blog/rstudio-1-4-a-quick-tour/#command-palette--shortcuts).\
  """

[usage_notice]
value = """\
  { pkg_intro_vignette <- stringr::str_replace_all(desc::desc_get_field('Package'), '\\\\.', '-'); \
    if (fs::file_exists(fs::path('vignettes', pkg_intro_vignette, ext = 'Rmd'))) \
      paste0('An introduction to this package is given [here](articles/', pkg_intro_vignette, '.html). ') \
    else '' \
  }\
  The (function) reference is found [here](reference).\
  """
