# R object types

[chr]
value = "[`character({length})`][base::character]"

[date]
value = "[`Date`][base::Date]"

[df]
value = "[`data.frame`][base::data.frame]"

[fct]
value = "[`factor`][base::factor]"

[int]
value = "[`integer({length})`][base::integer]"

[lgl]
value = "[`logical({length})`][base::logical]"

[list]
value = "[`list()`][base::list]"

[num]
value = "[`numeric({length})`][base::numeric]"

[pg_connection]
value = "[`PqConnection`][RPostgres::dbGetInfo_PqConnection]"
