# R object types

[chr]
value = "[`character({length})`][base::character]"

[date]
value = "[`Date`][base::Date]"

[int]
value = "[`integer({length})`][base::integer]"

[lgl]
value = "[`logical({length})`][base::logical]"

[num]
value = "[`numeric({length})`][base::numeric]"

[pg_connection]
value = "[`PqConnection`][RPostgres::dbGetInfo_PqConnection]"
