---
editor_options:
  markdown:
    references:
      prefix: "pkgpurl"
---

```{r}
#| include: false

link_r <- paste0("[`R/`](", pal::git_remote_tree_url(), "R/)")
link_rmd <- paste0("[`Rmd/`](", pal::git_remote_tree_url(), "Rmd/)")
```

This package's source code is written in the [R Markdown](https://rmarkdown.rstudio.com/) file format to facilitate practices commonly referred to as [*literate
programming*](https://en.wikipedia.org/wiki/Literate_programming). It allows the actual code to be freely mixed with explanatory and supplementary information
in expressive Markdown format instead of having to rely on [`#` comments](https://rstudio.github.io/r-manuals/r-lang/Parser.html#comments) only.

All the `.gen.R` suffixed R source code found under `r link_r` is generated from the respective R Markdown counterparts under `r link_rmd` using
[`pkgpurl::purl_rmd()`](https://pkgpurl.rpkg.dev/dev/reference/purl_rmd.html)[^pkgpurl-1]. Always make changes only to the `.Rmd` files -- never the `.R` files
-- and then run `pkgpurl::purl_rmd()` to regenerate the R source files.

[^pkgpurl-1]: The very idea to leverage the R Markdown format to author R packages was originally proposed by Yihui Xie. See his excellent [blog
    post](https://yihui.name/rlp/) for his point of view on the advantages of literate programming techniques and some practical examples. Note that using
    `pkgpurl::purl_rmd()` is a less cumbersome alternative to the Makefile approach outlined by him.
