---
editor_options:
  markdown:
    references:
      prefix: "rmd-pkg-n-"
---

```{r}
#| include: false
#| echo: false

# use `pkg_metadata` to customize URLs if available
url_r <- "R/"
url_rmd <- "Rmd/"

pal::assert_pkg("gert")
remotes <- try(gert::git_remote_list())

if (is.data.frame(remotes)) {
  
  url_git <-
    gert::git_remote_info()$url |>
    pal::when(stringr::str_detect(., "^git@") ~ stringr::str_replace_all(., c("(git@[\\w\\.]{1,}\\.[a-z]{2,}):" = "\\1/",
                                                                              "^git@" = "https://",
                                                                              "\\.git$" = "")),
              ~ .)
  add_slash_minus <- stringr::str_detect(url_git,
                                         "gitlab")
  url_git %<>% paste0("/-"[add_slash_minus], "/tree/", gert::git_branch(), "/")
  url_r %<>% paste0(url_git, .)
  url_rmd %<>% paste0(url_git, .)
}

link_r <- glue::glue("[`R/`]({url_r})")
link_rmd <- glue::glue("[`Rmd/`]({url_rmd})")
```

This package's source code is written in the [R Markdown](https://rmarkdown.rstudio.com/) file format to facilitate practices commonly referred to as [*literate
programming*](https://en.wikipedia.org/wiki/Literate_programming). It allows the actual code to be freely mixed with explanatory and supplementary information
in expressive Markdown format instead of having to rely on [`#` comments](https://cran.r-project.org/doc/manuals/r-release/R-lang.html#Comments) only.

All the `.gen.R` suffixed R source code found under `r link_r` is generated from the respective R Markdown counterparts under `r link_rmd` using
[`pkgpurl::purl_rmd()`](https://pkgpurl.rpkg.dev/dev/reference/purl_rmd.html)[^rmd-pkg-n--1]. Always make changes only to the `.Rmd` files -- never the `.R`
files -- and then run `pkgpurl::purl_rmd()` to regenerate the R source files.

[^rmd-pkg-n--1]: This naming convention as well as the very idea to leverage the R Markdown format to author R packages was originally proposed by Yihui Xie.
    See his excellent [blog post](https://yihui.name/rlp/) for more detailed information about the benefits of literate programming techniques and some
    practical examples. Note that using `pkgpurl::purl_rmd()` is a less cumbersome alternative to the Makefile approach outlined by him.
