# DO NOT EDIT THIS FILE BY HAND! Instead edit the R Markdown source file `Rmd/pkgsnippets.Rmd` and run `pkgpurl::purl_rmd()`.
# See `README.md#literate-programming` for more information on the literature programming approach used applying the R Markdown format.

utils::globalVariables(names = c("."))

#' Get snippet file path
#'
#' @param snippet The name of a snippet. Possible values include:
#'   `r paste0("- ``", fs::path_file(fs::dir_ls(path = system.file("snippets/", mustWork = TRUE, package = "pkgsnippets"), recurse = TRUE, type = "file")), "``")`
#'
#' @return A path of type [fs_path][fs::path()].
#' @export
#'
#' @examples
#' pkgsnippets::snippet_path("coding-style-notice.Rmd")
snippet_path <- function(snippet) {
  
  system.file("snippets/",
              mustWork = TRUE,
              package = utils::packageName()) %>%
    fs::dir_ls(recurse = TRUE,
               type = "file") %>%
    fs::path_file() %>%
    rlang::arg_match(arg = snippet) %>%
    paste0("snippets/", .) %>%
    system.file(mustWork = TRUE,
                package = utils::packageName()) %>%
    fs::path_real()
}
