# DO NOT EDIT THIS FILE BY HAND! Instead edit the R Markdown source file `Rmd/pkgsnip.Rmd` and run `pkgpurl::purl_rmd()`.
# See `README.md#r-markdown-format` for more information on the literate programming approach used applying the R Markdown format.

# pkgsnip: Standardized Labels, Messages and (R) Markdown Snippets for Package Authors
# Copyright (C) 2023 Salim Brüggemann
# 
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.

utils::globalVariables(names = c(".",
                                 "full_expressions",
                                 "label",
                                 "name",
                                 "path",
                                 "type",
                                 "value"))

this_pkg <- utils::packageName()

add_args_col <- function(data) {
  
  from_cols <- c("label", "value")
  
  from_col <-
    colnames(data) |>
    match(from_cols) %>%
    magrittr::extract(!is.na(.)) %>%
    {from_cols[.]} |> # nolint
    pal::when(length(.) == 0L ~ rlang::abort("No `from_col` could be determined!"),
              length(.) > 1L ~ rlang::abort("Multiple `from_col` candidates found:", pal::prose_ls(.,
                                                                                                   wrap = "`")),
              ~ .)
  
  dplyr::mutate(.data = data,
                arguments =
                  stringr::str_extract_all(string = !!rlang::sym(from_col),
                                           pattern = "(?<=\\{)[^\\}]+?(?=\\})") |>
                  purrr::map_chr(\(x) if (length(x) == 0L) "" else pal::prose_ls(x,
                                                                                 wrap = "`",
                                                                                 last_sep = ", ")))
}

backtickify_cols <- function(data,
                             cols = tidyselect::any_of(c("type", "name", "path"))) {
  
  dplyr::mutate(.data = data,
                dplyr::across({{cols}},
                              \(x) paste0("`", x, "`")))
}

#' List all available R Markdown file snippets
#' 
#' Lists all of the R Markdown snippets shipped with this package, together with the paths where they're located on the filesystem.
#'
#' @return `pkgsnip::return_label("data")`
#' @family rmdsnips
#' @export
ls_file_snips <- function() {
  
  fs::path_package("snippets/",
                   package = this_pkg) |>
    fs::dir_ls(recurse = TRUE,
               type = "file") |>
    tibble::tibble(path = _) |>
    dplyr::mutate(name = fs::path_file(path),
                  .before = 1L)
}

#' Get R Markdown snippet file path
#'
#' Returns the file path to an R Markdown snippet shipped with this package.
#'
#' The snippets can be used anywhere R Markdown input is supported. For example, you can use them as input to knitr's
#' [`child` document option](https://yihui.org/knitr/options/#child-documents):
#'
#' ````rmd
#' ```{r, child = pkgsnip::snip_path("installation-notice_dev-version_gitlab.Rmd")}
#' ```
#' ````
#'
#' Or you can use them in roxygen2's [`@includeRmd` tag](https://roxygen2.r-lib.org/articles/rd.html#including-external--rmd-md-files):
#'
#' ```r
#' #' @includeRmd `r pkgsnip::snip_path("installation-notice_dev-version_gitlab.Rmd")`
#' ```
#'
#' @param name The name of a snippet. Possible values include:
#' `r pal::as_md_val_list(ls_file_snips()$name)`
#'
#' @return `r return_lbl("path")`
#' @family rmdsnips
#' @export
#'
#' @examples
#' pkgsnip::snip_path("coding-style-notice.Rmd")
snip_path <- function(name = ls_file_snips()$name) {
  
  rlang::arg_match(name) %>%
    paste0("snippets/", .) |>
    fs::path_package(package = this_pkg) |>
    fs::path_real()
}

#' Markdown snippets
#'
#' A [tibble][tibble::tbl_df] with all Markdown snippets together with their `id`. The latter can be fed to [md_snip()].
#'
#' Currently, Markdown snippets with the following `id`s are available:
#'
#' ```{r, echo = FALSE}
#' data_md_snips |>
#'   dplyr::select(-value) |>
#'   backtickify_cols() |>
#'   pal::pipe_table()
#' ```
#'
#' @format `r return_lbl("data_cols", cols = colnames(data_md_snips))`
#' @family mdsnips
#' @export
#'
#' @examples
#' pkgsnip::data_md_snips
"data_md_snips"

#' Get predefined Markdown snippet
#'
#' @param id The snippet identifier. One of `r pal::prose_ls_fn_param(param = "id", fn = md_snip)`.
#' @param ... Further named arguments used to tailor the snippet to your needs. Not all snippets require additional arguments, see
#'   [`data_md_snips`][data_md_snips] for an overview. If a required argument is not explicitly provided, it is searched for in the [parent
#'   frames][parent.frame].
#'
#' @return A character scalar.
#' @family mdsnips
#' @export
#'
#' @examples
#' pkgsnip::md_snip(id = "rstudio_addin_hint") |> cat()
#'
#' # certain snips require additional args
#' pkgsnip::md_snip(id = "pkg_config",
#'                  pkg = "foo") |>
#'   cat()
md_snip <- function(id = data_md_snips$id,
                    ...) {
  
  id <- rlang::arg_match(id)
  env <- parent.frame()
  
  data_md_snips |>
    dplyr::filter(id == !!id) %$%
    value |>
    glue::glue(.envir = env,
               ... = ...)
}

#' Get a table of all available roxygen2 tag labels
#'
#' Returns a [tibble][tibble::tbl_df] listing all parameter labels included in this package, together with their `name` which can be provided as the `name`
#' argument of [param_label()] or [return_label()].
#'
#' Currently, parameter labels with the following `type`s and `name`s are available:
#'
#' ```{r, echo = FALSE}
#' roxy_labels() %>%
#'   add_args_col() %>%
#'   dplyr::select(-label) %>%
#'   backtickify_cols() %>%
#'   pal::pipe_table()
#' ```
#'
#' @param type The label type to return. A character scalar.
#'
#' @return `r return_lbl("data")`
#' @family roxygen2label
#' @export
roxy_labels <- function(type = c("any", "description", "param", "return", "title", NA_character_)) {
  
  type <- rlang::arg_match(type)
  
  data_roxy_lbls |>
    pal::when(type == "any" ~ .,
              is.na(type) ~ dplyr::filter(.data = .,
                                          is.na(type)),
              ~ dplyr::filter(.data = .,
                              type %in% c(!!type, NA_character_)))
}

#' @rdname roxy_labels
#' @export
roxy_lbls <- roxy_labels

#' Get predefined roxygen2 tag label
#'
#' Returns a pre-defined label intended to be used to document functions using [roxygen2][roxygen2::roxygen2]
#' [tags](https://roxygen2.r-lib.org/articles/rd.html#functions).
#'
#' The labels can be inserted using [inline \R code](https://roxygen2.r-lib.org/articles/rd-formatting.html#dynamic-r-code-1) as follows:
#'
#' ```r
#' #' @param start_date `r pkgsnip::roxy_lbl("start_date", type = "param")`
#' #' @return `r pkgsnip::roxy_lbl("data", type = "return")`
#' ```
#'
#' Note that the above only works in [roxygen2 7.1.0+](https://www.tidyverse.org/blog/2020/03/roxygen2-7-1-0/).
#' 
#' @param name The label name. See [roxy_labels()] for possible values.
#' @param ... Further named arguments used to tailor the label to your needs. Not all labels require additional arguments, see [roxy_labels()] for an overview.
#'   If a required argument is not explicitly provided, it is searched for in the [parent frames][parent.frame].
#'
#' @return A character vector.
#' @keywords internal
#' @family roxygen2label
#' @export
roxy_label <- function(name = roxy_labels()$name,
                       type = c("any", "description", "param", "return", "title", NA_character_),
                       ...) {
  
  name <- rlang::arg_match(name)
  env <- parent.frame()
  
  roxy_labels(type = type) |>
    dplyr::filter(name == !!name) |>
    # make sure labels of type `NA` come last
    dplyr::arrange(type) %$%
    label |>
    dplyr::first() |>
    glue::glue(.envir = env,
               ... = ...)
}

#' @rdname roxy_label
#' @export
roxy_lbl <- roxy_label

#' Get predefined `@description` label
#'
#' Returns a pre-defined label intended to be used as a function's description using [roxygen2][roxygen2::roxygen2]'s
#' [`@description`](https://roxygen2.r-lib.org/reference/tags-rd.html) tag.
#'
#' A label can be inserted using [inline \R code](https://roxygen2.r-lib.org/articles/rd-formatting.html#dynamic-r-code-1) as follows:
#'
#' ```r
#' #' @description `r pkgsnip::description_lbl("LABEL_NAME")`
#' ```
#' Note that the above only works in [roxygen2 7.1.0+](https://www.tidyverse.org/blog/2020/03/roxygen2-7-1-0/).
#'
#' Currently, the following `@description` labels are available:
#'
#' ```{r, echo = FALSE}
#' roxy_labels(type = "description") %>%
#'   add_args_col() %>%
#'   dplyr::select(-c(type, label)) %>%
#'   backtickify_cols() %>%
#'   pal::pipe_table()
#' ```
#' 
#' @inheritParams roxy_label
#'
#' @inherit roxy_label return
#' @family roxygen2label
#' @export
description_label <- function(name = roxy_labels(type = "description")$name,
                              ...) {
  
  roxy_label(name = rlang::arg_match(name),
             type = "description",
             ... = ...)
}

#' @rdname description_label
#' @export
description_lbl <- description_label

#' Get predefined `@param` label
#'
#' Returns a pre-defined label intended to be used to document a function parameter using [roxygen2][roxygen2::roxygen2]'s
#' [`@param`](https://roxygen2.r-lib.org/articles/rd.html#functions) tag.
#'
#' A label can be inserted using [inline \R code](https://roxygen2.r-lib.org/articles/rd-formatting.html#dynamic-r-code-1) as follows:
#'
#' ```r
#' #' @param PARAM_NAME `r pkgsnip::param_lbl("LABEL_NAME")`
#' ```
#' Note that the above only works in [roxygen2 7.1.0+](https://www.tidyverse.org/blog/2020/03/roxygen2-7-1-0/).
#'
#' Currently, the following parameter labels are available:
#'
#' ```{r, echo = FALSE}
#' roxy_labels(type = "param") %>%
#'   add_args_col() %>%
#'   dplyr::select(-c(type, label)) %>%
#'   backtickify_cols() %>%
#'   pal::pipe_table()
#' ```
#' 
#' @inheritParams roxy_label
#'
#' @inherit roxy_label return
#' @family roxygen2label
#' @export
param_label <- function(name = roxy_labels(type = "param")$name,
                        ...) {
  
  roxy_label(name = rlang::arg_match(name),
             type = "param",
             ... = ...)
}

#' @rdname param_label
#' @export
param_lbl <- param_label

#' Get predefined `@return` label
#'
#' Returns a pre-defined label intended to be used to document function return values using [roxygen2][roxygen2::roxygen2]'s
#' [`@return`](https://roxygen2.r-lib.org/articles/rd.html#functions) tag.
#'
#' A label can be inserted using [inline \R code](https://roxygen2.r-lib.org/articles/rd-formatting.html#dynamic-r-code-1) as follows:
#'
#' ```r
#' #' @return `r pkgsnip::return_lbl("LABEL_NAME")`
#' ```
#' Note that the above only works in [roxygen2 7.1.0+](https://www.tidyverse.org/blog/2020/03/roxygen2-7-1-0/).
#'
#' Currently, the following return labels are available:
#'
#' ```{r, echo = FALSE}
#' roxy_labels(type = "return") %>%
#'   add_args_col() %>%
#'   dplyr::select(-c(type, label)) %>%
#'   backtickify_cols() %>%
#'   pal::pipe_table()
#' ```
#' 
#' @inheritParams roxy_label
#'
#' @inherit roxy_label return
#' @family roxygen2label
#' @export
return_label <- function(name = roxy_labels(type = "return")$name,
                         ...) {
  
  roxy_label(name = rlang::arg_match(name),
             type = "return",
             ... = ...)
}

#' @rdname return_label
#' @export
return_lbl <- return_label

#' Get predefined `@title` label
#'
#' Returns a pre-defined label intended to be used to document a function's title using [roxygen2][roxygen2::roxygen2]'s
#' [`@title`](https://roxygen2.r-lib.org/reference/tags-rd.html) tag.
#'
#' A label can be inserted using [inline \R code](https://roxygen2.r-lib.org/articles/rd-formatting.html#dynamic-r-code-1) as follows:
#'
#' ```r
#' #' @title `r pkgsnip::title_lbl("LABEL_NAME")`
#' ```
#' Note that the above only works in [roxygen2 7.1.0+](https://www.tidyverse.org/blog/2020/03/roxygen2-7-1-0/).
#'
#' Currently, the following `@title` labels are available:
#'
#' ```{r, echo = FALSE}
#' roxy_labels(type = "title") %>%
#'   add_args_col() %>%
#'   dplyr::select(-c(type, label)) %>%
#'   backtickify_cols() %>%
#'   pal::pipe_table()
#' ```
#' 
#' @inheritParams roxy_label
#'
#' @inherit roxy_label return
#' @family roxygen2label
#' @export
title_label <- function(name = roxy_labels(type = "title")$name,
                        ...) {
  
  roxy_label(name = rlang::arg_match(name),
             type = "title",
             ... = ...)
}

#' @rdname title_label
#' @export
title_lbl <- title_label

#' \R condition messages
#'
#' A [tibble][tibble::tbl_df] with all \R condition messages included in this package, together with their `id`. The latter can be fed to [msg()].
#'
#' Currently, \R condition messages with the following `id`s and `arguments` are available:
#'
#' ```{r, echo = FALSE}
#' data_msgs |>
#'   add_args_col() |>
#'   dplyr::select(-value) |>
#'   backtickify_cols() |>
#'   pal::pipe_table()
#' ```
#'
#' @format `r return_lbl("data_cols", cols = colnames(data_msgs))`
#' @family rmsg
#' @export
"data_msgs"

#' Get predefined \R condition message
#'
#' @param id The message identifier. One of `r pal::prose_ls_fn_param(param = "id", fn = msg)`.
#' @param ... Further named arguments used to tailor the message to your needs. Not all messages require additional arguments, see [`data_msgs`][data_msgs] for
#'   an overview. If a required argument is not explicitly provided, it is searched for in the [parent frames][parent.frame].
#'
#' @return A character scalar.
#' @family rmsg
#' @export
#'
#' @examples
#' pkgsnip::msg(id = "pkg_required",
#'              pkg = "some_pkg")
msg <- function(id = data_msgs$id,
                ...) {
  
  id <- rlang::arg_match(id)
  env <- parent.frame()
  
  glue::glue(.envir = env,
             ... = ...,
             dplyr::filter(.data = data_msgs,
                           id == !!id)$value)
}

#' Commonly used abbreviations in \R code
#' 
#' Returns a [tibble][tibble::tbl_df] listing an opinionated set of abbreviations commonly used when writing \R code. It can be used as a reference, for
#' example, to check availability/consistency when considering using some abbreviation in a function or argument name.
#'
#' To avoid the list getting excessively long and redundant, **the main focus is on verbs and nouns**. Adjectives and adverbs are only listed in column
#' `full_expression` when there's not already a verb or noun with the same root word listed for a particular `abbreviation`. That means that e.g. the
#' abbreviation "seq" could also stand for the full expressions "sequential" or "sequentially", despite the fact that it is not explicitly listed but merely the
#' verb/noun "sequence" is.
#' 
#' @param unnest Whether to unnest the `full_expression` column and return the data in long format. If `FALSE`, a "nested" list column `full_expressions` will
#'   be returned, meaning the values in column `abbreviation` will be unique.
#' @return `r return_lbl("data")`
#' @export
#'
#' @examples
#' pkgsnip::abbrs(unnest = TRUE) |> print(n = Inf)
abbreviations <- function(unnest = FALSE) {
  
  checkmate::assert_flag(unnest)
  
  if (unnest) {
    data_abbrs %<>% tidyr::unnest_longer(col = full_expressions,
                                         values_to = "full_expression")
  }
  
  data_abbrs
}

#' @rdname abbreviations
#' @export
abbrs <- abbreviations
