# DO NOT EDIT THIS FILE BY HAND! Instead edit the R Markdown source file `Rmd/pkgsnip.Rmd` and run `pkgpurl::purl_rmd()`.
# See `README.md#r-markdown-format` for more information on the literate programming approach used applying the R Markdown format.

# pkgsnip: Standardized Labels, Messages and (R) Markdown Snippets for Package Authors
# Copyright (C) 2021 Salim Brüggemann
# 
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.

utils::globalVariables(names = c(".",
                                 "label",
                                 "name",
                                 "path",
                                 "snippet",
                                 "type"))

this_pkg <- utils::packageName()

add_args_col <- function(data) {
  
  from_cols <- c("label", "message")
  
  from_col <-
    colnames(data) %>%
    match(from_cols) %>%
    magrittr::extract(!is.na(.)) %>%
    {from_cols[.]} %>% # nolint
    purrr::when(length(.) == 0L ~ rlang::abort("No `from_col` could be determined!"),
                length(.) > 1L ~ rlang::abort("Multiple `from_col` candidates found:", pal::prose_ls(.,
                                                                                                     wrap = "`")),
                ~ .)
  
  dplyr::mutate(.data = data,
                arguments =
                  stringr::str_extract_all(string = !!rlang::sym(from_col),
                                           pattern = "(?<=\\{)[^\\}]+?(?=\\})") %>%
                  purrr::map_chr(~ pal::prose_ls(.x,
                                                 wrap = "`",
                                                 last_separator = ", ") %>%
                                   purrr::when(length(.) == 0L ~ "",
                                               ~ .)))
}

backtickify_cols <- function(data,
                             cols = tidyselect::any_of(c("type", "name", "path"))) {
  
  dplyr::mutate(.data = data,
                dplyr::across({{cols}},
                              ~ paste0("`", .x, "`")))
}

#' List all available R Markdown file snippets
#' 
#' Lists all of the R Markdown snippets shipped with this package, together with the paths where they're located on the filesystem.
#'
#' @return `pkgsnip::return_label("data")`
#' @family rmdsnips
#' @export
ls_file_snips <- function() {
  
  fs::path_package("snippets/",
                   package = this_pkg) %>%
    fs::dir_ls(recurse = TRUE,
               type = "file") %>%
    tibble::tibble(path = .) %>%
    dplyr::mutate(name = fs::path_file(path),
                  .before = 1L)
}

#' Get R Markdown snippet file path
#'
#' Returns the file path to an R Markdown snippet shipped with this package.
#'
#' The snippets can be used anywhere R Markdown input is supported. For example, you can use them as input to knitr's
#' [`child` document option](https://yihui.org/knitr/options/#child-documents):
#'
#' ````rmd
#' ```{r, child = pkgsnip::snip_path("installation-notice_dev-version_gitlab.Rmd")}
#' ```
#' ````
#'
#' Or you can use them in roxygen2's [`@includeRmd` tag](https://roxygen2.r-lib.org/articles/rd.html#including-external--rmd-md-files):
#'
#' ```r
#' #' @includeRmd `r pkgsnip::snip_path("installation-notice_dev-version_gitlab.Rmd")`
#' ```
#'
#' @param name The name of a snippet. Possible values include:
#'   00`r paste0('- ``"', ls_file_snips()$name, '"``')`
#'
#' @return `r pkgsnip::return_label("path")`
#' @family rmdsnips
#' @export
#'
#' @examples
#' pkgsnip::snip_path("coding-style-notice.Rmd")
snip_path <- function(name = ls_file_snips()$name) {
  
  rlang::arg_match(name) %>%
    paste0("snippets/", .) %>%
    fs::path_package(package = this_pkg) %>%
    fs::path_real()
}

#' Get a table of all Markdown snippets included in this package
#'
#' Returns a [tibble][tibble::tbl_df] listing all Markdown snippets together with their `name` which can be provided as [md_snip()]'s `name` argument.
#'
#' Currently, Markdown snippets with the following `names` are available:
#'
#' ```{r, echo = FALSE}
#' md_snips() %>%
#'   dplyr::select(-snippet) %>%
#'   backtickify_cols() %>%
#'   pal::pipe_table()
#' ```
#'
#' @return `r pkgsnip::return_label("data")`
#' @family mdsnips
#' @export
md_snips <- function() {
  
  tibble::tribble(
    ~name, ~snippet,
    "rstudio_addin_hint", paste0("This function is also registered as an [RStudio add-in](https://rstudio.github.io/rstudioaddins/) allowing RStudio users ",
                                 "to assign a custom shortcut to it."),
    "pkgdown_notice", "The documentation of this package is found [here]({pkgdown::as_pkgdown()$meta$url})."
  )
}

#' Get predefined Markdown snippet
#'
#' @param name The snippet name.
#' @param ... Further named arguments used to tailor the snippet to your needs. Not all snippets require additional arguments, see [md_snips()] for an overview.
#'   If a required argument is not explicitly provided, it is searched for in the [parent frames][parent.frame].
#'
#' @return A character scalar.
#' @family mdsnips
#' @export
md_snip <- function(name = md_snips()$name,
                    ...) {
  
  name <- rlang::arg_match(name)
  env = parent.frame()
  
  md_snips() %>%
    dplyr::filter(name == !!name) %$%
    snippet %>%
    glue::glue(.envir = env,
               ... = ...)
}

#' Get a table of all available roxygen2 tag labels
#'
#' Returns a [tibble][tibble::tbl_df] listing all parameter labels included in this package, together with their `name` which can be provided as the `name`
#' argument of [param_label()] or [return_label()].
#'
#' Currently, parameter labels with the following `type`s and `name`s are available:
#'
#' ```{r, echo = FALSE}
#' roxy_labels() %>%
#'   add_args_col() %>%
#'   dplyr::select(-label) %>%
#'   backtickify_cols() %>%
#'   pal::pipe_table()
#' ```
#'
#' @param type The label type to return. A character scalar.
#'
#' @return `r pkgsnip::return_label("data")`
#' @family roxygen2label
#' @export
roxy_labels <- function(type = c("any", "param", "return", NA_character_)) {
  
  type <- rlang::arg_match(type)
  
  tibble::tribble(
    ~type, ~name, ~label,
    NA, "data", "A [tibble][tibble::tbl_df].",
    NA, "date", "A [date][base::Date].",
    NA, "dates", "A vector of [dates][base::Date].",
    NA, "path", "A [path][fs::fs_path].",
    NA, "paths", "A vector of [paths][fs::fs_path].",
    NA, "r_object", "An \\R object.",
    NA, "response", "A [response object][httr::response].",
    NA, "strict_list", "A [strict list][xfun::strict_list()].",
    NA, "version_nr", "A [numeric version][numeric_version()].",
    NA, "opt_max_cache_lifespan", paste0("Note that [on package load][base::ns-hooks], the cache will be cleared from entries exceeding a global maximum ",
                                         "lifespan set by the [option][base::options()] `{this_pkg}.max_cache_lifespan` (defaults to `{max_cache_lifespan}` ",
                                         "if unset)."),
    "param", "cli_markup_support", "Supports cli's [inline markup][cli::inline-markup].",
    "param", "dyn_dots_support", "[Dynamic dots][rlang::dyn-dots] are supported.",
    "param", "eol", paste0("End of line (EOL) control character sequence. One of\n- `\"LF\"` for the line feed (LF) character (`\"\\n\"`). The standard on ",
                           "Unix and Unix-like systems (Linux, macOS, *BSD, etc.) and the **default**.\n- `\"CRLF\"` for the carriage return + line feed ",
                           "(CR+LF) character sequence (`\"\\r\\n\"`). The standard on Microsoft Windows, DOS and some other systems.\n- `\"CR\"` for the ",
                           "carriage return (CR) character (`\"\\r\"`). The standard on classic Mac OS and some other antiquated systems.\n- `\"LFCR\"` for ",
                           "the line feed + carriage return (LF+CR) character sequence (`\"\\n\\r\"`). The standard on RISC OS and some other exotic ",
                           "systems."),
    "param", "quiet", "Whether or not to suppress printing status output from internal processing.",
    "param", "start_date", "The begin of the period the data covers. A [date][base::Date] or a character scalar in the format `\"YYYY-MM-DD\"`.",
    "param", "end_date", "The end of the period the data covers. A [date][base::Date] or a character scalar in the format `\"YYYY-MM-DD\"`.",
    "param", "use_cache", "Return cached results if possible. If `FALSE`, results are always newly fetched regardless of `cache_lifespan`.",
    "param", "cache_lifespan", paste0("The duration after which cached results are refreshed (i.e. newly fetched). A valid ",
                                      "[lubridate duration][lubridate::as.duration]. Only relevant if `use_cache = TRUE`.")
  ) %>%
    purrr::when(type == "any" ~ .,
                is.na(type) ~ dplyr::filter(.data = .,
                                            is.na(type)),
                ~ dplyr::filter(.data = .,
                                type %in% c(!!type, NA_character_)))
}

#' @rdname roxy_labels
#' @export
roxy_lbls <- roxy_labels

#' Get predefined roxygen2 tag label
#'
#' Returns a pre-defined label intended to be used to document functions using [roxygen2][roxygen2::roxygen2]
#' [tags](https://roxygen2.r-lib.org/articles/rd.html#functions).
#'
#' The labels can be inserted using [inline \R code](https://roxygen2.r-lib.org/articles/rd-formatting.html#dynamic-r-code-1) as follows:
#'
#' ```r
#' #' @param start_date `r pkgsnip::roxy_label("start_date", type = "param")`
#' #' @return `r pkgsnip::roxy_label("data", type = "return")`
#' ```
#'
#' Note that the above only works in [roxygen2 7.1.0+](https://www.tidyverse.org/blog/2020/03/roxygen2-7-1-0/).
#' 
#' @param name The label name. See [roxy_labels()] for possible values.
#' @param ... Further named arguments used to tailor the label to your needs. Not all labels require additional arguments, see [roxy_labels()] for an overview.
#'   If a required argument is not explicitly provided, it is searched for in the [parent frames][parent.frame].
#'
#' @return A character vector.
#' @keywords internal
#' @family roxygen2label
#' @export
roxy_label <- function(name = roxy_labels()$name,
                       type = c("any", "param", "return", NA_character_),
                       ...) {
  
  name <- rlang::arg_match(name)
  env = parent.frame()
  
  roxy_labels(type = type) %>%
    dplyr::filter(name == !!name) %>%
    # make sure labels of type `NA` come last
    dplyr::arrange(type) %$%
    label %>%
    dplyr::first() %>%
    glue::glue(.envir = env,
               ... = ...)
}

#' @rdname roxy_label
#' @export
roxy_lbl <- roxy_label

#' Get predefined parameter label
#'
#' Returns a pre-defined label intended to be used to document function parameters using [roxygen2][roxygen2::roxygen2]'s
#' [`@param`](https://roxygen2.r-lib.org/articles/rd.html#functions) tag.
#'
#' A label can be inserted using [inline \R code](https://roxygen2.r-lib.org/articles/rd-formatting.html#dynamic-r-code-1) as follows:
#'
#' ```r
#' #' @param start_date `r pkgsnip::param_label("start_date")`
#' ```
#' Note that the above only works in [roxygen2 7.1.0+](https://www.tidyverse.org/blog/2020/03/roxygen2-7-1-0/).
#'
#' Currently, the following parameter labels are available:
#'
#' ```{r, echo = FALSE}
#' roxy_labels(type = "param") %>%
#'   add_args_col() %>%
#'   dplyr::select(-c(type, label)) %>%
#'   backtickify_cols() %>%
#'   pal::pipe_table()
#' ```
#' 
#' @inheritParams roxy_label
#'
#' @inherit roxy_label return
#' @family roxygen2label
#' @export
param_label <- function(name = roxy_labels(type = "param")$name,
                        ...) {
  
  roxy_label(name = rlang::arg_match(name),
             type = "param",
             ... = ...)
}

#' @rdname param_label
#' @export
param_lbl <- param_label

#' Get predefined return label
#'
#' Returns a pre-defined label intended to be used to document function return values using [roxygen2][roxygen2::roxygen2]'s
#' [`@return`](https://roxygen2.r-lib.org/articles/rd.html#functions) tag.
#'
#' A label can be inserted using [inline \R code](https://roxygen2.r-lib.org/articles/rd-formatting.html#dynamic-r-code-1) as follows:
#'
#' ```r
#' #' @return version_nr `r pkgsnip::return_label("version_nr")`
#' ```
#' Note that the above only works in [roxygen2 7.1.0+](https://www.tidyverse.org/blog/2020/03/roxygen2-7-1-0/).
#'
#' Currently, the following return labels are available:
#'
#' ```{r, echo = FALSE}
#' roxy_labels(type = "return") %>%
#'   add_args_col() %>%
#'   dplyr::select(-c(type, label)) %>%
#'   backtickify_cols() %>%
#'   pal::pipe_table()
#' ```
#' 
#' @inheritParams roxy_label
#'
#' @inherit roxy_label return
#' @family roxygen2label
#' @export
return_label <- function(name = roxy_labels(type = "return")$name,
                         ...) {
  
  roxy_label(name = rlang::arg_match(name),
             type = "return",
             ... = ...)
}

#' @rdname return_label
#' @export
return_lbl <- return_label

#' Get a table of all available \R condition messages
#'
#' Returns a [tibble][tibble::tbl_df] listing all \R condition messages included in this package, together with their `name` which can be provided as
#' [message()]'s `name` argument.
#'
#' Currently, \R condition messages with the following `names` and `arguments` are available:
#'
#' ```{r, echo = FALSE}
#' messages() %>%
#'   add_args_col() %>%
#'   dplyr::select(-message) %>%
#'   backtickify_cols() %>%
#'   pal::pipe_table()
#' ```
#'
#' @return `r pkgsnip::return_label("data")`
#' @family rmsg
#' @export
messages <- function() {
  
  tibble::tribble(
    ~name, ~message,
    "pkg_required", "To be able to use this function, the package '{this_pkg}' is required but it is not installed. Please install it and then try again."
  )
}

#' @rdname messages
#' @export
msgs <- messages

#' Get predefined \R condition message
#'
#' @param name The message name. See [messages()] for possible values.
#' @param ... Further named arguments used to tailor the message to your needs. Not all messages require additional arguments, see [messages()] for an
#'   overview. If a required argument is not explicitly provided, it is searched for in the [parent frames][parent.frame].
#'
#' @return A character scalar.
#' @family rmsg
#' @export
#'
#' @examples
#' pkgsnip::message(name = "pkg_required",
#'                  this_pkg = "some_pkg")
message <- function(name = messages()$name,
                    ...) {
  
  name <- rlang::arg_match(name)
  env = parent.frame()
  
  glue::glue(.envir = env,
             ... = ...,
             dplyr::filter(.data = messages(),
                           name == !!name)$message)
}

#' @rdname message
#' @export
msg <- message

#' Commonly used abbreviations in \R code
#' 
#' Returns a [tibble][tibble::tbl_df] listing an opinionated set of abbreviations commonly used when writing \R code. It can be used as a reference, for
#' example, to check availability when considering using some abbreviation in a function or argument name.
#' 
#' @param expand Whether to expand the full expression column and return the data in long format. If `FALSE`, a "nested" list column `full_expressions` will be
#'   returned, meaning the values in column `abbreviation` will be unique.
#' @return `r pkgsnip::return_label("data")`
#' @export
abbreviations <- function(expand = FALSE) {
  
  tibble::tribble(
    ~full_expressions, ~abbreviation,
    "abbreviation", "abbr",
    "abbreviations", "abbrs",
    "absolute", "abs",
    "argument", "arg",
    "arguments", "args",
    "attribute", "attr",
    "attributes", "attrs",
    c("authenticate", "authentication"), "auth",
    "authentications", "auths",
    "bibliography", "bib",
    "bibliographies", "bibs",
    "character", "chr",
    "characters", "chrs",
    "column", "col",
    "columns", "cols",
    "command", "cmd",
    "commands", "cmds",
    "combination", "combo",
    "combinations", "combos",
    "condition", "cnd",
    "conditions", "cnds",
    "configuration", "config",
    "configurations", "configs",
    "database", "db",
    "dataframe", "df",
    "dataframes", "dfs",
    "dataframe column", "dfc",
    "dataframe row", "dfr",
    "dependency", "dep",
    "dependencies", "deps",
    c("development", "developer"), "dev",
    c("developments", "developers"), "devs",
    "difference", "diff",
    "differences", "diffs",
    "directory", "dir",
    "directories", "dirs",
    "distribution", "distro",
    "distributions", "distros",
    "document", "doc",
    "documents", "docs",
    "double", "dbl",
    "doubles", "dbls",
    "element", "el",
    "elements", "els",
    "environment", "env",
    "environments", "envs",
    "exclude", "excl",
    "expression", "expr",
    "expressions", "exprs",
    "factor", "fct",
    "factors", "fcts",
    "filesystem", "fs",
    "formula", "fm",
    c("formulas", "formulae"), "fms",
    "function", "fn",
    "functions", "fns",
    c("generate", "generation"), "gen",
    "generations", "gens",
    "identifier", "id",
    "identifiers", "ids",
    "include", "incl",
    "index", "i",
    "indices/indexes", "ix",
    "information", "info",
    c("initialize", "initialization"), "init",
    "integer", "int",
    "integers", "ints",
    "label", "lbl",
    "labels", "lbls",
    "language", "lang",
    "languages", "langs",
    "level", "lvl",
    "levels", "lvls",
    "list", "ls",
    "logical", "lgl",
    "logicals", "lgls",
    "Markdown", "md",
    "message", "msg",
    "messages", "msgs",
    "modification", "mod",
    "modifications", "mods",
    "number", "nr",
    "numbers", "nrs",
    "number of", "n",
    "numeric", "num",
    "numerics", "nums",
    "object", "obj",
    "objects", "objs",
    "option", "opt",
    "options", "opts",
    "package", "pkg",
    "packages", "pkgs",
    "parameter", "param",
    "parameters", "params",
    "R Markdown", "rmd",
    "reference", "ref",
    "references", "refs",
    "regular expression(s)", "regex",
    "relative", "rel",
    "remove", "rm",
    "roxygen2", "roxy",
    c("separate", "separator"), "sep",
    "separators", "seps",
    c("sequential", "sequence"), "seq",
    "sequences", "seqs",
    c("specify", "specification"), "spec",
    "specifications", "specs",
    "string", "str",
    "strings", "strs",
    "temporary", "tmp",
    "value", "val",
    "values", "vals",
    "variable", "v",
    "variables", "vx",
    "vector", "vctr",
    "vectors", "vctrs"
  ) %>%
    purrr::when(expand ~ tidyr::unnest_longer(data = .,
                                              col = full_expressions,
                                              values_to = "full_expression"),
                ~ .)
}

#' @rdname abbreviations
#' @export
abbrs <- abbreviations
