# DO NOT EDIT THIS FILE BY HAND! Instead edit the R Markdown source file `Rmd/pkgsnip.Rmd` and run `pkgpurl::purl_rmd()`.
# See `README.md#r-markdown-format` for more information on the literature programming approach used applying the R Markdown format.

utils::globalVariables(names = c(".",
                                 "label",
                                 "name",
                                 "path",
                                 "type"))

pkg <- utils::packageName()

add_args_col <- function(data) {
  
  from_cols <- c("label", "message")
  
  from_col <-
    colnames(data) %>%
    match(from_cols) %>%
    magrittr::extract(!is.na(.)) %>%
    {from_cols[.]} %>%
    purrr::when(length(.) == 0L ~ rlang::abort("No `from_col` could be determined!"),
                length(.) > 1L ~ rlang::abort("Multiple `from_col` candidates found:", pal::prose_ls(.,
                                                                                                     wrap = "`")),
                ~ .)
  
  dplyr::mutate(.data = data,
                arguments =
                  stringr::str_extract_all(string = !!rlang::sym(from_col),
                                           pattern = "(?<=\\{)[^\\}]+?(?=\\})") %>%
                  purrr::map_chr(~ pal::prose_ls(.x,
                                                 wrap = "`",
                                                 last_separator = ", ") %>%
                                   purrr::when(length(.) == 0L ~ "",
                                               ~ .)))
}

backtickify_cols <- function(data,
                             cols = tidyselect::any_of(c("type", "name", "path"))) {
  
  dplyr::mutate(.data = data,
                dplyr::across({{cols}},
                              ~ paste0("`", .x, "`")))
}

#' List all available R Markdown file snippets
#' 
#' This function lists all of the R Markdown snippets shipped with this package, together with the paths where they're located on the filesystem.
#'
#' @return `pkgsnip::return_label("data")`
#' @family rmdsnips
#' @export
ls_file_snips <- function() {
  
  fs::path_package("snippets/",
                   package = pkg) %>%
    fs::dir_ls(recurse = TRUE,
               type = "file") %>%
    tibble::tibble(path = .) %>%
    dplyr::mutate(name = fs::path_file(path),
                  .before = 1L)
}

#' Get R Markdown snippet file path
#'
#' This function gives the file path to an R Markdown snippet shipped with this package.
#'
#' The snippets can be used anywhere R Markdown input is supported. For example, you can use them as input to knitr's
#' [`child` document option](https://yihui.org/knitr/options/#child-documents):
#'
#' ````rmd
#' ```{r, child = pkgsnip::snip_path("installation-notice_dev-version_gitlab.Rmd")}
#' ```
#' ````
#'
#' Or you can use them in roxygen2's [`@includeRmd` tag](https://roxygen2.r-lib.org/articles/rd.html#including-external--rmd-md-files):
#'
#' ```r
#' #' @includeRmd `r pkgsnip::snip_path("installation-notice_dev-version_gitlab.Rmd")`
#' ```
#'
#' @param name The name of a snippet. Possible values include:
#'   00`r paste0('- ``"', ls_file_snips()$name, '"``')`
#'
#' @return `r pkgsnip::return_label("path")`
#' @family rmdsnips
#' @export
#'
#' @examples
#' pkgsnip::snip_path("coding-style-notice.Rmd")
snip_path <- function(name = ls_file_snips()$name) {
  
  rlang::arg_match(name) %>%
    paste0("snippets/", .) %>%
    fs::path_package(package = pkg) %>%
    fs::path_real()
}

#' Get a table of all Markdown snippets included in this package
#'
#' This simply returns a [tibble][tibble::tbl_df] listing all Markdown snippets together with their `name` which can be provided as [md_snip()]'s `name`
#' argument.
#'
#' Currently, Markdown snippets with the following `names` are available:
#'
#' ```{r, echo = FALSE}
#' md_snips() %>%
#'   dplyr::select(-label) %>%
#'   backtickify_cols() %>%
#'   pal::pipe_table()
#' ```
#'
#' @return `r pkgsnip::return_label("data")`
#' @family mdsnips
#' @export
md_snips <- function() {
  
  tibble::tribble(
    ~name, ~label,
    "rstudio_addin_hint", paste0("This function is also registered as an [RStudio add-in](https://rstudio.github.io/rstudioaddins/) allowing RStudio users ",
                                 "to assign a custom shortcut to it.")
  )
}

#' Get predefined Markdown snippet
#'
#' @param name The snippet name.
#'
#' @return A character scalar.
#' @family mdsnips
#' @export
md_snip <- function(name = md_snips()$name) {
  
  name <- rlang::arg_match(name)
  
  dplyr::filter(.data = md_snips(),
                name == !!name)$label
  
  
}

#' Get a table of all available roxygen2 tag labels
#'
#' This simply returns a [tibble][tibble::tbl_df] listing all parameter labels included in this package, together with their `name` which can be provided as
#' the `name` argument of [param_label()] or [return_label()].
#'
#' Currently, parameter labels with the following `types` and `names` are available:
#'
#' ```{r, echo = FALSE}
#' roxy_labels() %>%
#'   add_args_col() %>%
#'   dplyr::select(-label) %>%
#'   backtickify_cols() %>%
#'   pal::pipe_table()
#' ```
#'
#' @param type The label type to return. A character scalar.
#'
#' @return `r pkgsnip::return_label("data")`
#' @family roxygen2label
#' @export
roxy_labels <- function(type = c("any", "param", "return", NA_character_)) {
  
  type <- rlang::arg_match(type)
  
  tibble::tribble(
    ~type, ~name, ~label,
    NA, "data", "A [tibble][tibble::tbl_df].",
    NA, "path", "A [path][fs::fs_path].",
    NA, "r_object", "An \\R object.",
    NA, "version_nr", "A [numeric version][numeric_version()].",
    NA, "opt_max_cache_lifespan", paste0("Note that [on package load][base::ns-hooks], the cache will be cleared from entries exceeding a global maximum ",
                                         "lifespan set by the [option][base::options()] `{pkg}.max_cache_lifespan` (defaults to `{max_cache_lifespan}` if ",
                                         "unset)."),
    "param", "dyn_dots_support", "[Dynamic dots][rlang::dyn-dots] are supported.",
    "param", "start_date", "The begin of the period the data covers. A [date][base::Date] or a character scalar in the format `\"YYYY-MM-DD\"`.",
    "param", "end_date", "The end of the period the data covers. A [date][base::Date] or a character scalar in the format `\"YYYY-MM-DD\"`.",
    "param", "use_cache", "Return cached results if possible. If `FALSE`, results are always newly fetched regardless of `cache_lifespan`.",
    "param", "cache_lifespan", paste0("The duration after which cached results are refreshed (i.e. newly fetched). A valid ",
                                      "[lubridate duration][lubridate::as.duration]. Only relevant if `use_cache = TRUE`.")
  ) %>%
    purrr::when(type == "any" ~ .,
                is.na(type) ~ dplyr::filter(.data = .,
                                            is.na(type)),
                ~ dplyr::filter(.data = .,
                                type %in% c(!!type, NA_character_)))
}

#' Get predefined roxygen2 tag label
#'
#' These are pre-defined labels intended to be used to document functions using [roxygen2][roxygen2::roxygen2]
#' [tags](https://roxygen2.r-lib.org/articles/rd.html#functions).
#'
#' The labels can be inserted using [inline R code](https://roxygen2.r-lib.org/articles/rd-formatting.html#dynamic-r-code-1) as follows:
#'
#' ```r
#' #' @param start_date `r pkgsnip::roxy_label("start_date", type = "param")`
#' #' @return `r pkgsnip::roxy_label("data", type = "return")`
#' ```
#'
#' Note that the above only works in [roxygen2 7.1.0+](https://www.tidyverse.org/blog/2020/03/roxygen2-7-1-0/).
#' 
#' @param name The label name. See [roxy_labels()] for possible values.
#' @param ... Further named arguments used to tailor the label to your needs. Not all labels require additional arguments, see [roxy_labels()] for an overview.
#'
#' @return A character vector.
#' @keywords internal
#' @family roxygen2label
#' @export
roxy_label <- function(name = roxy_labels()$name,
                       type = c("any", "param", "return", NA_character_),
                       ...) {
  
  name <- rlang::arg_match(name)
  
  roxy_labels(type = type) %>%
    dplyr::filter(name == !!name) %>%
    # make sure labels of type `NA` come last
    dplyr::arrange(type) %$%
    label %>%
    dplyr::first() %>%
    glue::glue(.envir = NULL,
               ... = ...)
}

#' Get predefined parameter label
#'
#' These are pre-defined labels intended to be used to document function parameters using [roxygen2][roxygen2::roxygen2]'s
#' [`@param`](https://roxygen2.r-lib.org/articles/rd.html#functions) tag.
#'
#' The following parameter labels are available to be inserted using [inline R code](https://roxygen2.r-lib.org/articles/rd-formatting.html#dynamic-r-code-1)
#' as follows:
#'
#' ```{r, echo = FALSE, results = "asis"}
#' bt <- "`"
#' roxy_labels(type = "param") %$%
#'   name %>%
#'   purrr::map_chr(~ glue::glue(bt, bt, "#' @@param {.x} ", bt, 'r pkgsnip::param_label("{.x}")', bt, " ", bt, bt)) %>%
#'   c("\n", .) %>%
#'   pal::cat_lines()
#' ```
#'
#' Note that the above only works in [roxygen2 7.1.0+](https://www.tidyverse.org/blog/2020/03/roxygen2-7-1-0/).
#' 
#' @inheritParams roxy_label
#'
#' @inherit roxy_label return
#' @family roxygen2label
#' @export
param_label <- function(name = roxy_labels(type = "param")$name,
                        ...) {
  
  roxy_label(name = rlang::arg_match(name),
             type = "param",
             ... = ...)
}

#' Get predefined return label
#'
#' These are pre-defined labels intended to be used to document function return values using [roxygen2][roxygen2::roxygen2]'s
#' [`@return`](https://roxygen2.r-lib.org/articles/rd.html#functions) tag.
#'
#' The following return labels are available to be inserted using [inline R code](https://roxygen2.r-lib.org/articles/rd-formatting.html#dynamic-r-code-1)
#' as follows:
#'
#' ```{r, echo = FALSE, results = "asis"}
#' bt <- "`"
#' roxy_labels(type = "return") %$%
#'   name %>%
#'   purrr::map_chr(~ glue::glue(bt, bt, "#' @@return ", bt, 'r pkgsnip::return_label("{.x}")', bt, " ", bt, bt)) %>%
#'   c("\n", .) %>%
#'   pal::cat_lines()
#' ```
#'
#' Note that the above only works in [roxygen2 7.1.0+](https://www.tidyverse.org/blog/2020/03/roxygen2-7-1-0/).
#' 
#' @inheritParams roxy_label
#'
#' @inherit roxy_label return
#' @family roxygen2label
#' @export
return_label <- function(name = roxy_labels(type = "return")$name,
                         ...) {
  
  roxy_label(name = rlang::arg_match(name),
             type = "return",
             ... = ...)
}

#' Get a table of all available R condition messages
#'
#' This simply returns a [tibble][tibble::tbl_df] listing all R condition messages included in this package, together with their `name` which can be provided
#' as [msg()]'s `name` argument.
#'
#' Currently, R condition messages with the following `names` and `arguments` are available:
#'
#' ```{r, echo = FALSE}
#' messages() %>%
#'   add_args_col() %>%
#'   dplyr::select(-message) %>%
#'   backtickify_cols() %>%
#'   pal::pipe_table()
#' ```
#'
#' @return `r pkgsnip::return_label("data")`
#' @family rmsg
#' @export
messages <- function() {
  
  tibble::tribble(
    ~name, ~message,
    "pkg_required", "To be able to use this function, the package '{pkg}' is required but it is not installed. Please install it and then try again."
  )
}

#' Get predefined R condition message
#'
#' @param name The message name. See [messages()] for possible values.
#' @param ... Further named arguments used to tailor the message to your needs. Not all messages require additional arguments, see [messages()] for an
#'   overview.
#'
#' @return A character scalar.
#' @family rmsg
#' @export
#'
#' @examples
#' pkgsnip::msg(name = "pkg_required",
#'              pkg = "some_pkg")
msg <- function(name = messages()$name,
                ...) {
  
  # ellipsis::check_dots_used()
  name <- rlang::arg_match(name)
  
  glue::glue(... = ...,
             dplyr::filter(.data = messages(),
                           name == !!name)$message)
}

#' Commonly used abbreviations in R code
#' 
#' This simply returns a [tibble][tibble::tbl_df] listing an opinionated set of abbreviations commonly used when writing R code. It can be used as a reference,
#' for example, to check availability when considering using a new abbreviation in a function or argument name.
#' 
#' @return `r pkgsnip::return_label("data")`
#' @export
abbreviations <- function() {
  
  tibble::tribble(
    ~full_expression, ~abbreviation,
    "absolute", "abs",
    "argument", "arg",
    "arguments", "args",
    "bibliography", "bib",
    "column", "col",
    "columns", "cols",
    "command", "cmd",
    "commands", "cmds",
    "combination", "combo",
    "combinations", "combos",
    "condition", "cnd",
    "conditions", "cnds",
    "database", "db",
    "difference", "diff",
    "differences", "diffs",
    "directory", "dir",
    "directories", "dirs",
    "distribution", "distro",
    "distributions", "distros",
    "document", "doc",
    "documents", "docs",
    "element", "el",
    "environment", "env",
    "environments", "envs",
    "exclude", "excl",
    "expression", "expr",
    "expressions", "exprs",
    "factor", "fct",
    "factors", "fcts",
    "filesystem", "fs",
    "function", "fn",
    "functions", "fns",
    "generate", "gen",
    "identifier", "id",
    "identifiers", "ids",
    "include", "incl",
    "index", "i",
    "indices/indexes", "ix",
    "information", "info",
    "initialization", "init",
    "label", "lbl",
    "labels", "lbls",
    "language", "lang",
    "level", "lvl",
    "levels", "lvls",
    "list", "ls",
    "Markdown", "md",
    "message", "msg",
    "messages", "msgs",
    "modification", "mod",
    "modifications", "mods",
    "number", "nr",
    "numbers", "nrs",
    "number of", "n",
    "object", "obj",
    "objects", "objs",
    "option", "opt",
    "options", "opts",
    "package", "pkg",
    "packages", "pkgs",
    "parameter", "param",
    "parameters", "params",
    "R Markdown", "rmd",
    "reference", "ref",
    "references", "refs",
    "regular expression(s)", "regex",
    "relative", "rel",
    "remove", "rm",
    "roxy", "roxygen2",
    "separator", "sep",
    "temporary", "temp",
    "variable", "v",
    "variables", "vx",
    "vector", "vctr",
    "vectors", "vctrs"
  )
}
